import { Geist, Geist_Mono } from "next/font/google";


import "./globals.css";
import Header from "@/components/Header";
import { CartProvider } from "@/contexts/CartContext";






export const metadata = {
  title: "Yum Town ",
  description: "Generated by Next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <CartProvider>
           <Header/>
           {children}
         </CartProvider>
      </body>
    </html>
  );
}
